[project]
name = "robot-server"
version = "0.1.0"
description = "This service provides a control and monitoring interface for the robot. It handles robot commands, sensor data collection, and logging. The backend is responsible for the robot's core logic, including navigation and room mapping. Additionally, it integrates a YOLO-based model for real-time human detection using camera input."
authors = [{ name = "Mikhail Drozdov", email = "deathlokmike@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "jinja2>=3.1.6",
    "numpy>=2.2.4",
    "ultralytics>=8.3.23",
    "uvicorn>=0.34.0",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "isort>=6.0.1",
    "ruff>=0.11.5",
]
